version: "3"
services:
  note:
    image: note
    ports:
      - "8080:8080"
    networks:
      - note-mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    networks:
      - note-mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/note?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root


networks:
  note-mysql:



